In [193]:
import requests
import pandas as pd

In [194]:
customers = pd.read_csv("customers.csv")
customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [195]:
customers=customers.drop_duplicates(subset=["first_name","last_name","city", "age","email"])

In [196]:
def fun1(city):
    if city=="cairo":
        return 'Cairo'
    elif city=='Alexandria':
      return 'Alexandria' 
    elif city=="Giza":
        return 'Giza'
    elif city=="Cairo":
           return 'Cairo'
    else :
        return "city"

In [197]:
customers['city'] = customers['city'].apply(fun1)

In [198]:
customers.dtypes

customer_id    int64
first_name       str
last_name        str
city             str
age            int64
email            str
dtype: object

In [199]:
customers['email']=customers['email'].fillna("unknwon@email.com ")

In [200]:
customers['full_name'] = customers['first_name'] + ' ' + customers['last_name']

In [201]:
customers

,customer_id,first_name,last_name,city,age,email,full_name
0,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan
1,2,Sara,Ali,Giza,31,sara@email.com,Sara Ali
2,3,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed
3,4,Mona,Ibrahim,Alexandria,28,unknwon@email.com,Mona Ibrahim

In [202]:
orders=pd.read_parquet("orders.parquet")
orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [203]:
orders.drop_duplicates()

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [204]:
orders.dtypes

order_id                int64
customer_id             int64
product_id              int64
quantity                int64
order_date     datetime64[us]
dtype: object

In [205]:
orders['quantity'].isna().sum()

np.int64(0)

In [206]:
invalid_qty = orders[orders['quantity'] <= 0]
print(invalid_qty)

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

In [207]:
products = pd.read_csv("https://raw.githubusercontent.com/MohammedHameds/test1455/refs/heads/main/products.csv")

products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [208]:
products.drop_duplicates()

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [209]:
products['category'] = products['category'].str.strip().str.title()
products['product_name'] = products['product_name'].str.strip().str.title()

In [210]:
products.dtypes

product_id      int64
product_name      str
category          str
unit_price      int64
dtype: object

In [211]:
products['unit_price'] = pd.to_numeric(products['unit_price'], errors='coerce')

In [212]:
orders = orders.drop_duplicates(subset=['order_id'])

In [213]:
sales = pd.merge(orders, customers, on='customer_id', how='left')
sales = pd.merge(sales, products, on='product_id', how='left')

In [214]:
sales

,order_id,customer_id,product_id,quantity,order_date,first_name,last_name,city,age,email,full_name,product_name,category,unit_price
0,1001,1,101,2,2026-09-01,Ahmed,Hassan,Cairo,25.0,ahmed@email.com,Ahmed Hassan,Laptop,Electronics,25000
1,1002,2,102,1,2026-09-01,Sara,Ali,Giza,31.0,sara@email.com,Sara Ali,Mouse,Accessories,500
2,1003,3,103,3,2026-09-02,Omar,Mohamed,Cairo,17.0,omar@email.com,Omar Mohamed,Keyboard,Accessories,1200
3,1004,4,101,1,2026-09-02,Mona,Ibrahim,Alexandria,28.0,unknwon@email.com,Mona Ibrahim,Laptop,Electronics,25000
4,1005,1,104,2,2026-09-03,Ahmed,Hassan,Cairo,25.0,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000
5,1006,5,102,1,2026-09-03,NaN,NaN,NaN,NaN,NaN,NaN,Mouse,Accessories,500
6,1007,2,105,4,2026-09-04,Sara,Ali,Giza,31.0,sara@email.com,Sara Ali,Headphones,Accessories,2500
7,1008,3,101,1,2026-09-04,Omar,Mohamed,Cairo,17.0,omar@email.com,Omar Mohamed,Laptop,Electronics,25000
8,1009,4,103,2,2026-09-05,Mona,Ibrahim,Alexandria,28.0,unknwon@email.com,Mona Ibrahim,Keyboard,Accessories,1200
9,1010,1,104,1,2026-09-05,Ahmed,Hassan,Cairo,25.0,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000

In [215]:
sales['total_amount'] = sales['quantity'] * sales['unit_price']
sales = sales.dropna(subset=['full_name'])
sales_final = sales[['order_id', 'full_name', 'product_name', 'quantity', 'unit_price', 'total_amount']]
sales_final = sales_final.rename(columns={'full_name': 'customer', 'product_name': 'product'})

In [216]:
sales_final

   order_id      customer     product  quantity  unit_price  total_amount
0      1001  Ahmed Hassan      Laptop         2       25000         50000
1      1002      Sara Ali       Mouse         1         500           500
2      1003  Omar Mohamed    Keyboard         3        1200          3600
3      1004  Mona Ibrahim      Laptop         1       25000         25000
4      1005  Ahmed Hassan     Monitor         2        7000         14000
6      1007      Sara Ali  Headphones         4        2500         10000
7      1008  Omar Mohamed      Laptop         1       25000         25000
8      1009  Mona Ibrahim    Keyboard         2        1200          2400
9      1010  Ahmed Hassan     Monitor         1        7000          7000

In [217]:
sales_final.to_csv("sales_final")

In [218]:
import pyodbc

conn = pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "server=.;"
    "database=sales_final;"
    "trusted_connection=yes;"
)

In [221]:
cursor = conn.cursor()

cursor.execute("""
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Sales')
    CREATE TABLE Sales (
        order_id INT,
        customer NVARCHAR(100),
        product NVARCHAR(100),
        quantity INT,
        unit_price FLOAT,
        total_amount FLOAT
    )
""")
conn.commit()

In [222]:
for index, row in sales_final.iterrows():
    cursor.execute(
        "INSERT INTO Sales (order_id, customer, product, quantity, unit_price, total_amount) VALUES (?, ?, ?, ?, ?, ?)",
        row['order_id'], row['customer'], row['product'], row['quantity'], row['unit_price'], row['total_amount']
    )

conn.commit()

In [229]:
from flask import Flask, render_template
import pyodbc
import pandas as pd

app = Flask(__name__)

def get_sales_data():
    conn = pyodbc.connect(
        "driver={ODBC Driver 17 for SQL Server};"
        "server=.;"
        "database=sales_final;"
        "trusted_connection=yes;"
    )
    df = pd.read_sql("SELECT * FROM Sales", conn)
    conn.close()
    return df

@app.route('/')
def dashboard():
    try:
        df = get_sales_data()
        return render_template(
            'dashboard.html',
            data=df.to_dict(orient='records'),
            columns=df.columns.tolist()
        )
    except Exception as e:
        return f"<h2>An error occurred:</h2><pre>{e}</pre>"

if __name__ == '__main__':
    app.run(debug=True, use_reloader=False)

 * Serving Flask app '__main__'
 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit

C:\Users\Win -11\AppData\Local\Temp\ipykernel_29168\2580820793.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Sales", conn)
127.0.0.1 - - [22/Sep/2026 22:25:13] "GET / HTTP/1.1" 200 -